### ISSUE TITLE
MinGW updates

### ISSUE THREAD

**Issue by jpcima** [DISTRHO/juce#11]
Regarding the limitations in MinGW builds, set by commit a770b17:

I'm rather sure that this functionality is working on modern MinGW because these work on personal builds based on upstream JUCE.

I think it needs some reevaluation based on more recent MinGW compiler abilities.
(or possibly, it's a case of WINNT version set too low in the Windows build)

**Comment by falkTX** [comment]
I am fine with that too, since now my mingw is updated too (using v7)

**Comment by falkTX** [comment]
As of now in the `main` branch, these changes are no longer there.
The compat branch likely still has them, but I am not actively updating that anymore, only there so a few old plugins can still build.
