### ISSUE TITLE
plugin won't build with this fork but builds with original JUCE

### ISSUE THREAD

**Issue by rghvdberg** [DISTRHO/juce#3]
On Ubuntu 16.04.2

I'm trying to build this plugin https://github.com/rghvdberg/the-source/tree/linux
With the JUCE from https://www.juce.com/ it compiles cleanly, with the DISTRHO fork it fails

####  What I did

- configure `~build/the-source/plugin/plugin.jucer` with original Projucer.
Set module paths to` ~build/JUCE/modules`
- renamed `Makefile` to` Makefile.orig`
- `make -f Makefile.orig` builds successfully
- compile Projucer from the DISTRHO fork
- configure `plugin.jucer` with `~build/juce/extras/Projucer/Builds/LinuxMakefile/build/Projucer`
- set module paths to `~build/juce/modules`
- rename `Makefile` to `Makefile.distrho`
- run `make -f Makefile.disthro clean`
- run `make -f Makefile.disthro V=1`
- build fail
output of last command here http://pastebin.com/n2d6prNU

**Comment by falkTX** [comment]
Likely fixed now, please retest.
Thank you.

**Comment by falkTX** [comment]
ping, need some retest..

**Comment by falkTX** [comment]
Fully rebased, should work now as stock replacement.
Current `main` branch follows juce 6.0.4, while `distrho-ports-compat` has older code that is frozen in order to support building the older distrho-ports plugins.
